### ISSUE TITLE
problem deploy hdp cluster

### ISSUE THREAD

**Issue by akarray** [GoogleCloudPlatform/bdutil#16]
Hello,

When I launch the deploy command : ./bdutil -e platforms/hdp/ambari_env.sh deploy

The deployment end with errors :

..Wed Feb 11 15:59:12 CET 2015: Command failed: wait ${SUBPROC} on line 308.
Wed Feb 11 15:59:12 CET 2015: Exit code of failed command: 1
Wed Feb 11 15:59:12 CET 2015: Detailed debug info available in file: /tmp/bdutil-20150211-155631-ezD/debuginfo.txt
Wed Feb 11 15:59:12 CET 2015: Check console output for error messages and/or retry your command.
iMac-de-****_:bdutil-vc a**_**$ cat  /tmp/bdutil-20150211-154518-AeG/debuginfo.txt

When I explore the error file /tmp/bdutil-20150211-154518-AeG/debuginfo.txt

***********\* ERROR logs from gcloud compute stderr ************
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].

Problem seem come internally from bdutil generated command : 

 gcloud --project=xxxxxxxx --quiet --verbosity=info compute ssh hadoop-w-0 --command=exit 0 --ssh-flag=-oServerAliveInterval=60 --ssh-flag=-oServerAliveCountMax=3 --ssh-flag=-oConnectTimeout=30 --zone=europe-west1-c

Some one know how resolve this issue ?

Thanks

**Comment by pmkc** [comment]
Are you able to use gcloud compute to ssh into those instances or others in that zone?

**Comment by pmkc** [comment]
My mistake it was actually a combination of a number of factors, but essentially assigning a bash "readonly" variable twice.

It should be fixed in https://github.com/GoogleCloudPlatform/bdutil/pull/17.

**Comment by akarray** [comment]
Greet.
All is Ok now!

**Comment by bryan4887** [comment]
I am getting the same error.  `gcloud compute ssh <instance>` works for me though.  Here's a section of the output:

```
Sat Mar 21 20:39:23 CST 2015: Warning. Failed to delete all staging files.
Sat Mar 21 20:39:23 CST 2015: Invoking on workers: ./ambari-setup.sh
....Sat Mar 21 20:39:24 CST 2015: Invoking on master: ./ambari-setup.sh
.Sat Mar 21 20:39:24 CST 2015: Waiting on async 'ssh' jobs to finish. Might take a while...
Sat Mar 21 20:39:58 CST 2015: Exited 1 : gcloud --project=xxxx --quiet --verbosity=info compute ssh hadoop-w-0 --command=sudo su -l -c "cd ${PWD} && ./ambari-setup.sh" 2>>ambari-setup_deploy.stderr 1>>ambari-setup_deploy.stdout --ssh-flag=-tt --ssh-flag=-oServerAliveInterval=60 --ssh-flag=-oServerAliveCountMax=3 --ssh-flag=-oConnectTimeout=30 --zone=us-central1-a
```

In the debuginfo.txt, the problem area seems to be with the ssh command:

```
ssh: connect to host 130.211.xxx.xxx port 22: Connection refused
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

The weird thing is that this worked for me the first time I went through but now it doesn't.  Any suggestions?

**Comment by dennishuo** [comment]
That appears to be a transient error which should be solvable by retrying your deployment. If you find a case where a GCE VM never becomes ssh-able, please send your project details to a Google cloud-support team, or email gcp-hadoop-contact@google.com and someone can take a closer look at the faulty VM.
