### ISSUE TITLE
bdutil - on server stop/start - hdfs not able to find fs

### ISSUE THREAD

**Issue by blogmaniak** [GoogleCloudPlatform/bdutil#40]
Instead of having to delete the bdutil, we were hoping to stop and restart the server to avoid having to setup the spark applications from start. Also, on delete it deletes hdfs and we loose all the model data that we generated. However, on restart hdfs goes into safe mode and does not recognize the fs.

Following are the two messages that we see at this time:
Safe mode is ON. The reported blocks 0 needs additional 10 blocks to reach the threshold 0.9990 of total blocks 10. The number of live datanodes 0 has reached the minimum number 0. Safe mode will be turned off automatically once the thresholds have been reached.

Zero blocklocations for /Cluster/WSSE. Name node is in safe mode. The reported blocks 0 needs additional 10 blocks to reach the threshold 0.9990 of total blocks 10. The number of live datanodes 0 has reached the minimum number 0. Safe mode will be turned off automatically once the thresholds have been reached.

Also, i tried to force it out of safemode but got the following message:
vibhu@anintelcluster:/home/hadoop/hadoop-install/bin$ ./hdfs dfsadmin -safemode leave
15/07/03 19:42:27 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.4.0-hadoop2
safemode: FileSystem gs://anintelcluster/ is not an HDFS file system
Usage: hdfs dfsadmin [-safemode enter | leave | get | wait]

Please let us know if we don't have the option to stop/start - or is there something we can do on restart and get hdfs out of safe mode.

**Comment by dennishuo** [comment]
I can try to repro this. While bdutil doesn't have built-in commands for "stopping" and "starting" a cluster, there are various flavors of stopping/starting which are indeed supported.

How did you "stop" and "restart" your cluster? Did you only stop/restart your master, or did you do it on every node? Are you using Local SSDs, and are you using USE_ATTACHED_PDS?

**Comment by blogmaniak** [comment]
This example was based on single node using the following command:
./bdutil deploy -e hadoop2_env.sh --bucket anintelcluster -e single_node_env.sh -e spark_env.sh -P anintelcluster
All I did was top the single node. However, when I bring it up, even though the hadoop and spark services are running, my application is not able to access them via configured URL e.g. hadoop URL is hdfs://anintelcluster:8020.
The way I stopped was using the developer console - Compute>VM>select VM>Stop/Start.
Re: HDD - I use whatever is default for the bdutil script - no changes to that.

**Comment by dennishuo** [comment]
Alright, I did manage to repro. There might be some race-condition that's more specific to a single-node environment during startup. I was able to repair HDFS simply by running:

```
/home/hadoop/hadoop-install/sbin/stop-all.sh
/home/hadoop/hadoop-install/sbin/start-all.sh
```

When I did that I was able to access my old data inside HDFS again that I added prior to the stop/start. I'll check on why the automatic restart didn't work.

EDIT: Forgot to mention, you have to run those scripts as user `hadoop`, so first run `sudo su hadoop`.

**Comment by dennishuo** [comment]
Alright, tracked down the bug to configure_startup_processes.sh and spark_configure_startup_processes.sh not correctly adding worker daemons in the case of single-node clusters. This bug only affects clusters which use single_node_env.sh. I've successfully tested a fix and sent a pull request which we'll merge shortly: https://github.com/GoogleCloudPlatform/bdutil/pull/42

You can optionally clone from my fork in the meantime to check it out: https://github.com/dennishuo/bdutil

Or it should it make it into the master within a couple days.

**Comment by dennishuo** [comment]
https://github.com/GoogleCloudPlatform/bdutil/pull/42 has been merged, issue should be fixed now if you use bdutil at head revision.

**Comment by blogmaniak** [comment]
Confirm bug fixed ..
