### ISSUE TITLE
testing spark 1.5 .. issue with tar

### ISSUE THREAD

**Issue by desaiak** [GoogleCloudPlatform/bdutil#59]
I pointed the SHARK_HADOOP2_TARBALL_URI to spark-1.5.0-bin-hadoop2.6.tgz file I downloaded and places on gcs.
Downloading file:///home/hadoop/spark-1.5.0-bin-hadoop2.6.tgz:   302.98 MiB/302.98 MiB
hadoop-m:t
hadoop-m:tgzip: stdin: not in gzip format
hadoop-m:ttar: Child returned status 1
hadoop-m:ttar: Error is not recoverable: exiting now
hadoop-m:t.

I am able to run tar -C spark -xzvf spark-1.5.0-bin-hadoop2.6.tgz on my mac where I downloaded the file, however it does throw and error 
tar: copyfile unpack (spark-1.5.0-bin-hadoop2.6/python/test_support/sql/orc_partitioned/SUCCESS.crc) failed: No such file or directory

I saw this issue mentioned here -> http://apache-spark-developers-list.1001551.n3.nabble.com/VOTE-Release-Apache-Spark-1-5-0-RC2-tp13826p13893.html

Any idea how to resolve this?

**Comment by dennishuo** [comment]
Can you try our hosted version of that for which we've validated checksums, etc., and see if it works?

SPARK_HADOOP1_TARBALL_URI='gs://spark-dist/spark-1.5.0-bin-hadoop1.tgz'
SPARK_HADOOP2_TARBALL_URI='gs://spark-dist/spark-1.5.0-bin-hadoop2.6.tgz'

**Comment by desaiak** [comment]
Yep that worked .. thanks.
Closing.
