### ISSUE TITLE
bdutil extenstion for Apache Tajo

### ISSUE THREAD

**Issue by ykko** [GoogleCloudPlatform/bdutil#68]
Hi,
It seems that yshan's contribution is waiting for review. His contribution is a bdutil extention for Apache Tajo, an open source SQL-on-Hadoop system (http://tajo.apache.org). The extension enables Google cloud users to deploy and setup Tajo cluster and start their big data analysis on GCP.

Can you please review the request? 
https://github.com/GoogleCloudPlatform/bdutil/pull/67

Youngkyong

**Comment by hys9958** [comment]
Hi @AngusDavis ,
I have updated the #67 about your comment.
Thanks!!

**Comment by dennishuo** [comment]
Closed by https://github.com/GoogleCloudPlatform/bdutil/commit/91ab4cc26ff3fd3cf20bd7d82bcde1c0b8d3147a
