### ISSUE TITLE
Command failed line 326, and SSH Key

### ISSUE THREAD

**Issue by papagunit** [GoogleCloudPlatform/bdutil#81]
Hi all,
New user to bdutil, running on cygwin in win 7, followed instructions in readme, encountered this error:
Command failed: wait ${SUBPROC} on line 326.
Exit code of failed command: 1

Please reference [this gist](https://gist.github.com/papagunit/d8217476a013aa10805010ee1715374f).

Any suggestions?

I am able to execute the socksproxy or ssh tunnel, but am unable to get them to work. Here is the [terminal output](https://gist.github.com/papagunit/bcf59fc61adf7fe8586ca581b5e20ceb) while trying ssh.

Thanks!

**Comment by AngusDavis** [comment]
Hi papagunit - 

In the second gist, you were successfully logged in to the hadoop master node via SSH. The second gcloud config-ssh command failed as the default credential exposed to GCE VMs has limited access to APIs and resources.  You can expand the scopes that are exposed by adding entries to GCE_SERVICE_ACCOUNT_SCOPES in bdutil_env.sh (e.g., add compute-rw to give access to read/write GCE resources).

Once you've opened a socksproxy to the master, you should be able to initiate a browser session using the emitted command line to configure chrome or firefox and navigate to hadoop-m:8080 and log in to Ambari to see where it failed in its setup.

**Comment by papagunit** [comment]
I've gotten `error_message='Could not add SSH key to project metadata:'` once in awhile, but have tended to ignore it as it doesn't happen every time. I just delete and deploy again.
However, when I tried your suggestion, it eventually worked! I just modified the env to GCE_SERVICE_ACCOUNT_SCOPES=('storage-full',compute-rw).
Thank you!
